# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:lastest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - 8080:8080
    volumes:
      -.postgres/:var/lib/postgresql/data
